# Generated by Django 3.2.5 on 2021-07-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20210709_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.lot'),
        ),
    ]
