# Generated by Django 3.2.5 on 2021-07-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210709_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='finished_bet_id',
            new_name='finished_bet',
        ),
    ]
